name: CI
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - name: Deploying
        env:
          TOKEN: ${{ secrets.AUTH_TOKEN }}
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: ci
